export default {
   Typhoid: [
        'a) Florpheucal',
        '   15-30mg',
        '   PO (in drinking water)',
        '   3-5 days',
        '\n',
        'b) Brufen',
        '   5-10mg/kg',
        '   2 days',
        '\n',
        'c) ADEK',
        '   1g per 1-2 l',
        '   5 days',
        '\n',
        '     OR   ',
        '\n',
        'a) Sulpha',
        '   Trimethaprin 8%',
        '   Sulphadiazine 40%',
        '   15 mg/kg',
        '   3 Days + 2 Days',
        '\n',
        'b) Brufen',
        '   5-10mg/kg',
        '   2 days',
        '\n',
        'c) ADEK',
        '   1g per 1-2 l',
        '   5 days'
   ],
   ND: [
        'a) Lysoit',
        '   1ml/litre',
        '   5 days',
        '\n',
        'b) VitEd Sol',
        '   10y -> 1ml/2l',
        '   20y -> 1ml/1l',
        '\n',
        'c) Vitamin C',
        '   20-50mg/kg',
        '   5 days'
   ],
   Cocci: [
        'a) Ampolium',
        '   13-30mg/kg',
        '\n',
        'b) Brufen',
        '   5-10mg/kg',
        '   2 days',
        'c) ADEK',
        '   1g per 1-2 l',
        '   5 days',
        '\n',
        '     OR   ',
        '\n',
        'a) Sulpha',
        '   Trimethaprin 8%',
        '   Sulphadiazine 40%',
        '   15 mg/kg',
        '   3 Days + 2 Days',
        '\n',
        'b) Brufen',
        '   5-10mg/kg',
        '   2 days',
        '\n',
        'c) ADEK',
        '   1g per 1-2 l',
        '   5 days'
   ]
};